### ISSUE TITLE
javaArrayIndexOutOfBoundException

### ISSUE THREAD

**Issue by aloklearning** [erikagtierrez/multiple-media-picker#8] opened 2017-10-05 06:26 UTC
Since your library works fine for me but one thing I noticed is that, when you select a video from the folder and come out and select some other video from another folder it works fine. But as soon as you want to deselect the previous selection it throws an error and stops. The error goes like this.

`java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
                                                                         at java.util.ArrayList.remove(ArrayList.java:480)
                                                                         at com.erikagtierrez.multiple_media_picker.OpenGallery$3.onClick(OpenGallery.java:95)
                                                                         at com.erikagtierrez.multiple_media_picker.OpenGallery$RecyclerTouchListener.onInterceptTouchEvent(OpenGallery.java:146)
                                                                         at android.support.v7.widget.RecyclerView.dispatchOnItemTouch(RecyclerView.java:2702)
                                                                         at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2830)
                                                                         at android.view.View.dispatchTouchEvent(View.java:10067)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2776)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2408)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
                                                                         at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:435)
                                                                         at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1836)
                                                                         at android.app.Activity.dispatchTouchEvent(Activity.java:3063)
                                                                         at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
                                                                         at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
                                                                         at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:397)
                                                                         at android.view.View.dispatchPointerEvent(View.java:10298)
                                                                         at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4928)
                                                                         at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4787)
                                                                         at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4293)
                                                                         at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4346)
                                                                         at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4312)
                                                                         at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4459)
                                                                         at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4320)
                                                                         at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4516)
                                                                         at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4293)
                                                                         at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4346)
                                                                         at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4312)
                                                                         at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4320)
                                                                         at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4293)
                                                                         at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6817)
                                                                         at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6791)
                                                                         at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6734)
                                                                         at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6989)
                                                                         at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                         at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                         at android.os.MessageQueue.next(MessageQueue.java:328)
                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6251)
10-05 11:52:16.375 27336-27336/in.pinelane.testapp E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1075)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)`

**Comment by JosephM3388** [comment] 2017-11-07 00:23
Have you also gotten this error when not selecting a media and pressing the check button?

**Comment by aloklearning** [comment] 2017-11-07 06:27
nopes when I check some images from another folder and then come to other folder check some more images and then when I go back to the same folder from where I started to uncheck my previous selections it happens.

**Comment by erikagtierrez** [comment] 2017-11-24 14:22
Duplicate of #7

**Closed as completed by erikagtierrez** 2017-11-24 14:22 UTC
